### ISSUE TITLE
API/ABI break: associate behaviour flags with client object instead of for each function call

### ISSUE THREAD

**Issue by kaniini** [pkgconf/pkgconf#105]
This makes things more consistent and allows for cleaner implementation of some things (like prefix relocation), but breaks ABI.  Thusly it cannot go back to 1.1 series.

**Comment by plicease** [comment]
I think this is the right approach.  Also my Perl module already does this, so even it breaks my code it shouldn't break my interface.

**Comment by kaniini** [comment]
And that is that.
