### ISSUE TITLE
Regression in pkgconf 1.2.0

### ISSUE THREAD

**Issue by ant1** [pkgconf/pkgconf#108]
With pkgconf 1.1.1,  I had

```
% pkgconf --print-variables pkg-config
pc_path
% pkgconf --variable=pc_path pkgconfig
/usr/local/libdata/pkgconfig:/usr/libdata/pkgconfig
```

With pkgconf 1.2.0,  I have

```
% pkgconf --print-variables pkg-config
pc_path
% pkgconf --variable=pc_path pkg-config

```

**Comment by ant1** [comment]
It seems the regression was introduced in [https://github.com/pkgconf/pkgconf/commit/7b39c38408889c4a2a18e8dc3b2fedada5bc94ed](https://github.com/pkgconf/pkgconf/commit/7b39c38408889c4a2a18e8dc3b2fedada5bc94ed)

**Comment by bapt** [comment]
Thanks for reporting, fixed in 7d89f65

**Comment by bapt** [comment]
Actually 5e5c418 is the proper fix

**Comment by kaniini** [comment]
1.2.1 will have the fix, thanks for reporting.
