### ISSUE TITLE
Website references a different git repo than https://github.com/pkgconf/pkgconf/

### ISSUE THREAD

**Issue by bgoodr** [pkgconf/pkgconf#117]
Please update the main website at https://www.freedesktop.org/wiki/Software/pkg-config/ to point to the correct repo. If this repo is the correct one, then why is there a different one mentioned on the website at https://cgit.freedesktop.org/pkg-config ?

**Comment by kaniini** [comment]
There are two 'mainstream' implementations of pkg-config.  That's the freedesktop implementation, which is different than ours.  We made pkgconf (and distributions have adopted pkgconf) for various reasons which are covered in the README.
