### ISSUE TITLE
split pkgconf core into libpkg library

### ISSUE THREAD

**Issue by kaniini** [pkgconf/pkgconf#12]
so we can have other clients like gcc -framework patch

**Comment by kaniini** [comment]
@wycats out of curiosity, would an API giving you a pre-formatted string be useful?  or do you just want to iterate over the raw `pkg_fragment_t`'s like pkgconf itself does?

**Comment by wycats** [comment]
What would the preformatted string look like?

**Comment by kaniini** [comment]
the pre-formatted string would be basically, the same result as `pkgconf --cflags` or `pkgconf --libs`.  the reason why i mentioned the lower-level option is because it may be more useful to you to get at the lower-level flags so that you can translate them as needed for Rust.

**Comment by wycats** [comment]
I could see some benefit from both options. The preformatted string would be easier to migrate from, but the lower level option would give us more control in the long term. 

Any reason not to do both?

**Comment by kaniini** [comment]
There's no problem with providing both interfaces.

In that case, would an interface like:

   pkgconf_err_return_t pkgconf_pkg_cflags_as_string(pkg_t *root, char *buffer, size_t size, int maxdepth, unsigned int flags);

work for you guys?

The only downside is that it would use a buffer, so really long cflags strings might be truncated.

**Comment by kaniini** [comment]
Only a few things remaining here.  Most likely this is being cut as of end of next week!

- [ ] handle `pc_sysrootdir` and other builtins (probably have a function to optionally install these)
- [ ] handle fragment rendering to string and updating the CLI client to use it (not a big deal)

**Comment by plicease** [comment]
Is there any documentation (aside from `libpkgconf.h`) or examples (aside from main.c)?  Something like this:  https://github.com/libarchive/libarchive/wiki/Examples would be helpful for getting started?

**Comment by kaniini** [comment]
We are working on docs for it, but haven't really decided our plan there yet.  We will probably go with Sphinx or similar and include some examples, but the cleanup isn't fully done yet so right now I'm concentrating on that.

**Comment by kaniini** [comment]
This is probably complete enough to close out.
