### ISSUE TITLE
Build error with mingw

### ISSUE THREAD

**Issue by maxinbjohn** [pkgconf/pkgconf#121]
Hi,

This commit fixes some build errors with mingw:

From 4d7b4d7c8e9966c593f472355607204c6c80fecb Mon Sep 17 00:00:00 2001
From: Dan Kegel <dank@kegel.com>
Date: Sun, 4 Jun 2017 19:19:55 -0700
Subject: [PATCH] Minimal tweaks to compile with Visual C 2015

However, this introduces the following build error in mingw due to case sensitive header file name:

| compilation terminated.
| In file included from ../pkgconf-1.3.7/libpkgconf/libpkgconf.h:19:0,
|                  from ../pkgconf-1.3.7/libpkgconf/audit.c:16:
| ../pkgconf-1.3.7/libpkgconf/stdinc.h:36:12: fatal error: BaseTsd.h: No such file or directory
|  #  include <BaseTsd.h>
|             ^~~~~~~~~~~

Updating " BaseTsd.h" to " basetsd.h" works here for mingw. 
" 
Microsoft's documentation and usage itself is inconsistent:
http://msdn.microsoft.com/en-us/library/windows/desktop/aa383751%28v=vs.85%29.aspx
uses "BaseTsd.h",
http://msdn.microsoft.com/en-us/library/windows/desktop/aa384267%28v=vs.85%29.aspx
and
http://msdn.microsoft.com/en-us/library/windows/desktop/aa384268%28v=vs.85%29.aspx
mention "Basetsd.h", the header file identifies itself as "basetsd.h" and the
header files in the Windows 7 SDK which include it use "basetsd.h" too (see
Fci.h, Fdi.h, MMC.h, MMC.idl, MSClus.h, MSCluc.idl etc.).
"
Further explanation is available here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=675801

**Comment by kaniini** [comment]
I merged your patch for it.
