### ISSUE TITLE
The sysroot is duplicated when using ${pc_sysrootdir}/${prefix} or similar

### ISSUE THREAD

**Issue by hwti** [pkgconf/pkgconf#123]
With wayland-protocols.pc, with https://lists.freedesktop.org/archives/wayland-devel/2017-July/034419.html applied :
```
prefix=/usr
datarootdir=${prefix}/share
pkgdatadir=${pc_sysrootdir}/${datarootdir}/wayland-protocols

Name: Wayland Protocols
Description: Wayland protocol files
Version: 1.9
```

```
$ PKG_CONFIG_SYSROOT_DIR=/sysroot pkgconf --variable=pkgdatadir wayland-protocols
/sysroot//sysroot/usr/share/wayland-protocols
```

So when using ${pc_sysrootdir} to make pkg-config work, it breaks pkgconf.
Since pkgconf seems to add the sysroot to all variables looking like an absolute path, I think it should check for duplicates when a variable starts with ${pc_sysrootdir}.

**Comment by kaniini** [comment]
interestingly, it's supposed to be checking.  i'm going to dig on this.

**Comment by hwti** [comment]
Thanks
