### ISSUE TITLE
Meson build doesn't install pkg.m4

### ISSUE THREAD

**Issue by Earnestly** [pkgconf/pkgconf#124]
I was recently trying out your meson build and while it built nicely I hadn't noticed that it didn't install the `pkg.m4` file.  This resulted in a bunch of older projects still using autoconf failing with awkward syntax errors as they attempted to use the `PKG_CHECK_MODULE` macro.

Could the meson build still include `pkg.m4` for legacy projects?

*PS: Can you make the tests using kyua optional?*

**Comment by kaniini** [comment]
meson support is still under construction :)

**Comment by Earnestly** [comment]
Yeah I know, hence this report.  Just trying it out
