### ISSUE TITLE
gpaste with pkgconf problem with PKG_PREREQ

### ISSUE THREAD

**Issue by kapouer** [pkgconf/pkgconf#127]
Hi,

i just noticed that https://github.com/Keruspe/GPaste failed to build with pkgconf, and not with pkg-config.
The error is: `possibly undefined macro: PKG_PREREQ`

**Comment by kaniini** [comment]
pkgconf 1.3 series includes the necessary macro, it is new.  it will fail to build with pkg-config < 0.29.2 as well.
