### ISSUE TITLE
pkgconf_path_match_list() doesn't use relocated path it produces

### ISSUE THREAD

**Issue by karen-arutyunov** [pkgconf/pkgconf#129]
Implementation of pkgconf_path_match_list() function has the following code:

if (pkgconf_path_relocate(relocated, sizeof relocated))
  cpath = path;

It looks wrong. Shouldn't it be:

if (pkgconf_path_relocate(relocated, sizeof relocated))
  cpath = relocated;

**Comment by kaniini** [comment]
A fix will be available in pkgconf 1.3.9.
