### ISSUE TITLE
Removing  _GNU_SOURCE macro definition from stdinc.h

### ISSUE THREAD

**Issue by karen-arutyunov** [pkgconf/pkgconf#135]
Could you remove  _GNU_SOURCE from stdinc.h, which is implicitly get defined in the library client code when libpkgconf.h is included?

One of the problems is that if this macro is already defined in the client code (for example g++ defines it by default in contrast to gcc), then the "redefined macro" warning is issued.

This macro is only required for the library source code compilation, so can safely be moved to source files that require it.

**Comment by kaniini** [comment]
actually, the macro is not required at all, and i have no idea how it got there, so i removed it.
