### ISSUE TITLE
Manual page is missing the m4 macros

### ISSUE THREAD

**Issue by ebassi** [pkgconf/pkgconf#147]
Since pkgconf replaces the `pkg-config.1` man page (at least, it does on Fedora 26), it would be nice if the manual page for pkgconf kept the bits about the Autconf m4 macros for integrating pkg-config into an Autotools project.

I know that we kind of dislike Autotools, but the macros section of the pkg-config manual page was the only way to check for the available macros and their syntax.

**Comment by kaniini** [comment]
The person who contributed the manpage didn't look at the pkg-config one, so we weren't aware that the autoconf m4 macros are mentioned.  Would you happen to have some example text to provide guidance for those users?

**Comment by ebassi** [comment]
The current `pkg-config.1` man page has a whole section on the available macros [here](https://cgit.freedesktop.org/pkg-config/tree/pkg-config.1#n440).

Since pkgconf ships with a `pkg.m4`, it should probably take a similar approach, and list each available macro, alongside the documentation blurb from the m4 file.
