### ISSUE TITLE
Suspicious code in pkgconf_fragment_should_munge()

### ISSUE THREAD

**Issue by karen-arutyunov** [pkgconf/pkgconf#152]
The loop over check_fragments array elements in pkgconf_fragment_should_munge() function looks either redundant or out of order. The strncmp() call inside the loop can never return 0 as its first argument (the string parameter) always starts with '/' character and the second (check_fragments[i].token) with '-', and so the loop can never end up returning true.

Also looks a bit strange that if the loop end up returning true, then the string that starts with an option (for example -isystem) would be prepended with the sysroot_dir (see pkgconf_fragment_munge()).

**Comment by kaniini** [comment]
It was there for historical reasons, it's obsolete now.
