### ISSUE TITLE
Improve pkg-config command bash completion

### ISSUE THREAD

**Issue by swilmet** [pkgconf/pkgconf#155]
Improve pkg-config command bash completion.

Fedora has switched to pkgconf, but the bash completion is not as good as with pkg-config.

More precisely, the completion of the option *names* like `--modversion`.

**Comment by kaniini** [comment]
Freedesktop `pkg-config` does not provide a bash-completion file.  If there was one, it was specific to the fedora packaging.

I don't think it is appropriate to include a bash completion file with pkgconf, because other people would want other shell completion files, too.

**Comment by swilmet** [comment]
I find it a bit strange to implement that downstream in each distro.

**Comment by swilmet** [comment]
I think the only problem that I have with the bash completion with pkgconf is:
https://github.com/pkgconf/pkgconf/issues/157
