### ISSUE TITLE
--modversion missing in pkg-config --help

### ISSUE THREAD

**Issue by swilmet** [pkgconf/pkgconf#157]
`--modversion` is missing in `pkg-config --help`.

I've opened this issue for bash-completion:
https://github.com/scop/bash-completion/issues/176
because with pkgconf there is no completion of the `--modversion` pkg-config option name. But the bash-completion issue was closed because what they do is to parse the output of `pkg-config --help` to know the list of options.

**Comment by kaniini** [comment]
That is indeed a good catch, thank you for reporting!

**Comment by swilmet** [comment]
Thanks, I'm glad the problem is fixed.
