### ISSUE TITLE
MSVC issues 'void function returning a value' warning

### ISSUE THREAD

**Issue by karen-arutyunov** [pkgconf/pkgconf#162]
Compiling the latest master branch with MSVC (with /W3 option) get the following warning: 

```
libpkgconf/fragment.c(538): warning C4098: 'pkgconf_fragment_render_buf': 'void' function returning a value
```

**Comment by karen-arutyunov** [comment]
Btw if you grant me a commit access, I could fix such trivial things rather than report.

**Comment by kaniini** [comment]
Sent an invite for it.

**Comment by karen-arutyunov** [comment]
Got it, thanks.

**Comment by kaniini** [comment]
Should be working.

**Comment by karen-arutyunov** [comment]
Yeah, successfully joined.
