### ISSUE TITLE
Backslash escaping in CFlags is parsed incorrectly

### ISSUE THREAD

**Issue by karen-arutyunov** [pkgconf/pkgconf#163]
The following cflags representations are equivalent according to the shell quoting rules:

```
Cflags: "-IC:\\D E"
Cflags: '-IC:\D E'
Cflags: -IC:\\D\ E
```

This assumption is confirmed by ‘pkg-config --cflags’, that prints them all the same:

```
-IC:\\D\ E
```

However, pkgconf (latest master) prints them all differently:

```
'-IC:\D E' 
'-IC:D E'
'-IC:\\D E'
```

It’s a valid choice to print the flag single-quoted (in contrast to pkg-config) in the presence of spaces, but it still should be printed the same for all 3 cases:

```
'-IC:\D E'
```

I think that the problem starts in libpkgconf at the stage of parsing flags string into the list of pkgconf_fragment_t structures. The resulted pkgconf_fragment_t objects contains the following data for the above cases:

```
C:\D E
C:D E
C:\\D E
```

This looks broken, as the library client could expect all 3 forms to result in the same (most natural “fully unescaped/unquoted”) internal representation:
  
```
C:\D E
```

**Comment by kaniini** [comment]
Yes, there seems to be more escape-related deficiencies.

Sigh, I will deal with that tonight.
