### ISSUE TITLE
improved cross-compile/multiarch support using personality files

### ISSUE THREAD

**Issue by kaniini** [pkgconf/pkgconf#166]
Right now the preferred approach for cross-compiling with pkgconf is to write a wrapper script that describes the target to pkgconf.  By adding a simple shim layer, we could replace this with a simple configuration file instead.

Using `argv[0]` we can deduce whether or not we are running in native mode or cross mode.

If we are in native mode, we just load `default.personality` from the configuration dir.  If we are in cross mode, then we just load `*triplet*.personality` from the configuration dir.

A cross-compiler config may look something like:

```
Personality: i386-adelie-linux-musl
SystemIncludePaths: /usr/i386-adelie-linux-musl/include
SystemLibraryPaths: /usr/i386-adelie-linux-musl/lib
DefaultSearchPaths: /usr/i386-adelie-linux-musl/lib/pkgconfig /usr/i386-adelie-linux-musl/share/pkgconfig
```

In this example, the cross-compiler is actually just the i386 compiler running on an x86_64 host, but it is important to note that the paths are relative to the sysroot, like you would do with a real cross-compiler.  In other words, multi-arch and cross-compilers should be handled the same by pkgconf.

I would like to move the compiled-in data to the `default.personality` file so that the site administrator can more easily configure the tool's default behaviour.  Perhaps a combination of `/usr/share/pkgconf/personalities/default.personality` and `/etc/pkgconf-personalities.d/default.personality` to allow site-specific customization of any personality.

cc @ignatenkobrain

**Comment by Conan-Kudo** [comment]
Yes, it'd be quite nice to be able to replace what I've done here: https://src.fedoraproject.org/rpms/pkgconf/c/cf41f5098b598217c3745f6ddf3a5dade608cf0a

**Comment by ignatenkobrain** [comment]
This sounds good to me!

**Comment by kaniini** [comment]
yes i need to sort out meson and cmake files.  i'll do it in a bit.
