### ISSUE TITLE
./libtool: line 2621: func__fatal_error: command not found

### ISSUE THREAD

**Issue by SpaceboyRoss01** [pkgconf/pkgconf#169]
Whenever I configure with these arguments `CC=/home/spaceboyross/BlueSkyOS/modules/syscore/./src/rootfs/bin/musl-gcc --prefix=/home/spaceboyross/BlueSkyOS/modules/syscore/./src/rootfs --exec-prefix=/home/spaceboyross/BlueSkyOS/modules/syscore/./src/rootfs/usr --with-system-libdir=/home/spaceboyross/BlueSkyOS/modules/syscore/./src/rootfs/lib:/home/spaceboyross/BlueSkyOS/modules/syscore/./src/rootfs/usr/lib --with-system-includedir=/home/spaceboyross/BlueSkyOS/modules/syscore/./src/rootfs/usr/include --host=x86_64 --target=x86_64 CFLAGS="-shared"` and try to make, I get:
```
make[1]: Entering directory '/home/spaceboyross/BlueSkyOS/modules/syscore/src/pkgconf'
  CC       libpkgconf/client.lo
./libtool: line 2621: func__fatal_error: command not found
mv: cannot stat 'libpkgconf/.deps/client.Tpo': No such file or directory
Makefile:741: recipe for target 'libpkgconf/client.lo' failed
make[1]: *** [libpkgconf/client.lo] Error 1
make[1]: Leaving directory '/home/spaceboyross/BlueSkyOS/modules/syscore/src/pkgconf'
src/config/targets/pkgconf/build.mk:2: recipe for target 'pkgconf' failed
make: *** [pkgconf] Error 2
```
Can someone fix this?

**Comment by kaniini** [comment]
your libtool is broken, it is not a pkgconf issue

**Comment by SpaceboyRoss01** [comment]
But I just installed libtool today on Ubuntu 17.10.

**Comment by kaniini** [comment]
then you should probably have a word with ubuntu, as we just use the system libtool.

beyond that, your CFLAGS are quite strange which likely indicates other breakage.  you may want to look into why you need to explicitly specify `-shared` in your CFLAGS, as you usually shouldn't be doing that.

either way, it is not a pkgconf issue.

hope that is helpful.
