### ISSUE TITLE
libtool:   error: cannot build a shared library See the libtool documentation for more information. Fatal configuration error.

### ISSUE THREAD

**Issue by SpaceboyRoss01** [pkgconf/pkgconf#170]
I compiled libtool myself because Ubuntu has an older or broken version and using `CC=/home/spaceboyross/BlueSkyOS/modules/syscore/./src/rootfs/bin/musl-gcc --prefix=/home/spaceboyross/BlueSkyOS/modules/syscore/./src/rootfs --exec-prefix=/home/spaceboyross/BlueSkyOS/modules/syscore/./src/rootfs/usr --with-system-libdir=/home/spaceboyross/BlueSkyOS/modules/syscore/./src/rootfs/lib:/home/spaceboyross/BlueSkyOS/modules/syscore/./src/rootfs/usr/lib --with-system-includedir=/home/spaceboyross/BlueSkyOS/modules/syscore/./src/rootfs/usr/include --host=x86_64 --target=x86_64 CFLAGS="-shared"` in the configuration causes:
```
make[1]: Entering directory '/home/spaceboyross/BlueSkyOS/modules/syscore/src/pkgconf'
  CC       libpkgconf/fragment.lo
libtool:   error: cannot build a shared library See the libtool documentation for more information. Fatal configuration error.
Makefile:743: recipe for target 'libpkgconf/fragment.lo' failed
make[1]: *** [libpkgconf/fragment.lo] Error 1
make[1]: Leaving directory '/home/spaceboyross/BlueSkyOS/modules/syscore/src/pkgconf'
src/config/targets/pkgconf/build.mk:2: recipe for target 'pkgconf' failed
make: *** [pkgconf] Error 2
```
I have to add `CFLAGS="-shared"` or else there will be an error saying that it cannot be linked (causes `configure: error: C compiler cannot create executables` without shared enabled because I use musl for the libc in my distro called BlueSkyOS, Version 0.2.0-beta).

**Comment by kaniini** [comment]
you are doing weird things with your toolchain, this isn't the appropriate place for support.  maybe try contacting the musl list for help with your toolchain.
