### ISSUE TITLE
pkg-config compatibility issues on Windows

### ISSUE THREAD

**Issue by jmoguillansky-gpsw** [pkgconf/pkgconf#207]
Hi, 
I'm trying to switch from "pkg-config" (https://www.freedesktop.org/wiki/Software/pkg-config) to pkg-conf on windows.  
I noticed some slight compatibility issues:

When running pkg-config on windows:

Called `C:\...\pkg-config.EXE sdl2 --libs` -> 0
-L -L/manual-link -lSDL2 -lSDL2main -ldinput8 -lshell32 -lsetupapi -ladvapi32 -luuid -lversion -loleaut32 -lole32 -limm32 -lwinmm -lgdi32 -luser32 -lSDL2

When running pkg-conf on windows:

Called `C:\...\pkg-config.EXE sdl2 --libs` -> 0
-L -lSDL2 -L/manual-link -lSDL2main

I think adding param "--static" results in a more similar output.

Please advise.

I also noticed some other compatibility issues on windows: backslashes instead of forward slashes?
I'm using pkg-config indirectly via meson build system, so it's not easy for me to just change the params passed to pkg-config.  
I would need to submit a PR or an issue to meson on github, etc.

**Comment by kaniini** [comment]
Most likely Windows should assume `--static --pure`, which is inappropriate for ELF environments for shared linking.

A patch accepting that is welcome (as is changing the path format), but I do not personally have any interest in Windows support -- the Windows-using community will need to come to a consensus and make it behave as they wish it to on Windows.
