### ISSUE TITLE
[RFC] Slightly rework Windows path handling to be more pkg-config compatible

### ISSUE THREAD

**Issue by lazka** [pkgconf/pkgconf#212]
In MSYS2 we've switched from pkg-config to pkgconf some weeks ago for native Windows builds and had to patch some things regarding directory separators to fix some builds and make the meson test suite pass. It's been working nicely since then.

It mainly comes down to this patch: https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-pkgconf/0004-fix-prefix-dirsep.patch (this is against the last release, so for master there are more changes/reverts)

* Don't normalize "\\" to "/" at the end as it breaks escaping of spaces etc
* Assume path values in the .pc file either use "/" (preferred) or "\\\\" (escaped backslash). This makes Windows less of a special case again.
* When inserting the relocation prefix escape it and convert "\\" to "/" first, so that in combination with the .pc content we have a valid path value again.

I'd try to clean this up and create a PR if this is something that seems acceptable.

**Comment by kaniini** [comment]
This seems fine to me.

**Comment by kaniini** [comment]
@lazka do you have time to look at this?

**Comment by lazka** [comment]
sorry, yes, today or tomorrow.

**Comment by lazka** [comment]
See #216 and #217

**Comment by lazka** [comment]
Thanks you! If there are any Windows related issues feel free to ping me.
