### ISSUE TITLE
CMake build not supported

### ISSUE THREAD

**Issue by Alexpux** [pkgconf/pkgconf#233]
Need cleanup README and remove info about cmake build as it not supported now

**Comment by webbtrail** [comment]
I have put together a CMake solution for building this project.  Is that a contribution you would like?

**Comment by dg0yt** [comment]
I'm not a maintainer, but I think the decision was made 5 years ago, in favor of Meson.
https://github.com/pkgconf/pkgconf/commit/7a395932f2ff68c2f0f5dda556de2345df5be353
https://github.com/pkgconf/pkgconf/blob/2d26db3a984e7a69cedc6274c22119de4bcf1b40/NEWS#L342-L343
