### ISSUE TITLE
missing functions with musl

### ISSUE THREAD

**Issue by annacrombie** [pkgconf/pkgconf#244]
When compiling `pkgconf` on musl with meson, there are several missing functions: `strdup`, `strcasecmp`, and `strncasecmp`.  The resulting pkgconf is unusable, segfaulting early in startup.  

If you look at the [musl source](https://git.musl-libc.org/cgit/musl/tree/include/string.h#n62), it looks like one of `_POSIX_SOURCE`, `_POSIX_C_SOURCE`, `_XOPEN_SOURCE`, `_GNU_SOURCE`, `_BSD_SOURCE` must be defined for `strdup` to be visible.

In the case of `strcasecmp` and `strncasecmp`, you are missing an `#include <strings.h>` (note the `s`).  The reason it works without this include on glibc is in the man page:

> The strcasecmp() and strncasecmp() functions first appeared in 4.4BSD,
> where they were declared in <string.h>.  Thus, for reasons of
> historical compatibility, the glibc <string.h> header file also
> declares these functions, if the _DEFAULT_SOURCE (or, in glibc 2.19 and
> earlier, _BSD_SOURCE) feature test macro is defined.

**Comment by Olf0** [comment]
> In the case of `strcasecmp` and `strncasecmp`, you are missing an `#include <strings.h>` (note the `s`).

Or use `_GNU_SOURCE` or `_BSD_SOURCE` (which both catch both issues), see https://git.musl-libc.org/cgit/musl/tree/include/string.h#n62

**Comment by Olf0** [comment]
Oh, this was already addressed on 21 Feb 2022 by commits https://github.com/pkgconf/pkgconf/commit/cf48b61a59c1ce6c55a3066a940a6821b9f937bf, https://github.com/pkgconf/pkgconf/commit/cc4ccc1429f79df8db4d0a84f4c1581d36b41576 and https://github.com/pkgconf/pkgconf/commit/40131312ec5e774cafa71a922311693b6bed853f.
