### ISSUE TITLE
PKG_CONFIG_SYSROOT_DIR incompatible between pkg-config and pkgconf

### ISSUE THREAD

**Issue by circl-lastname** [pkgconf/pkgconf#251]
Here's the behavior as per the pkg-config manpage:
> PKG_CONFIG_SYSROOT_DIR
Modify -I and -L to use the directories located in target sysroot. this option is usefull when crosscompiling package that use pkg-config to determine CFLAGS anf LDFLAGS. -I and -L are modified to point to the new system root. this means that a -I/usr/include/libfoo will become -I/var/target/usr/include/libfoo with a PKG_CONFIG_SYSROOT_DIR equal to /var/target (same rule apply to -L) 

and per the pkgconf manpage:
>PKG_CONFIG_SYSROOT_DIR
sysroot directory, will be prepended to every path defined in PKG_CONFIG_PATH.  Useful for cross compilation.

In fact, pkgconf does not modify the -I and -L arguments to respect the sysroot, which breaks cross-compilation. Additionally, pkg-config doesn't seem to do anything with its PATH using this variable. I believe this is unintentional.

**Comment by circl-lastname** [comment]
> Again this was implemented in this way intentionally because everyone agreed that the pkg-config behaviour was broken. We can add an option to force the pkg-config behaviour. The default behaviour in regards to sysroot is not likely to change without a much stronger rationale than "pkg-config does it that way." We made pkgconf, because we felt that pkg-config had deficits in many areas.

I found this in an earlier thread about this topic, does this apply to here? Arch Linux stopped providing pkg-config and only has pkgconf + other alternatives, which at that point I would take to the maintainers to tell them that in fact pkgconf is not always pkg-config

**Comment by kaniini** [comment]
Use `PKG_CONFIG_FDO_SYSROOT_RULES=1` if you want the freedesktop pkg-config sysroot behavior.  The defaults are changed in pkgconf for a reason: almost no .pc file supports SYSROOT the way the pkg-config authors wanted it implemented.  This is why distributions keep using pkgconf instead of pkg-config.

**Comment by circl-lastname** [comment]
Hi, sorry for the late response, but this seems to do the opposite of what I want. It seems in the code to specifically *disable* appending the sysroot. I need the sysroot appended for any headers to be found. Changing this flag doesn't seem to do anything for me. I'm not sure where it is failing.

**Comment by kaniini** [comment]
That is what pkgconf does by default.  pkg-config *only* does it if `${pc_sysrootdir}` is set in .pc files.
