### ISSUE TITLE
Add support for --define-prefix by default on non-Windows

### ISSUE THREAD

**Issue by geofft** [pkgconf/pkgconf#253]
Hi! I'm trying to use pkgconf in a development setup where built packages are always relocated between when they're compiled and when they're used as build-dependencies. One issue I'm running into is that we need to use `--define-prefix` to make this work, but most upstream build systems don't provide a way to set arguments to `pkg-config`.

The original pkg-config project has a `./configure --enable-define-prefix` option to implicitly do `--define-prefix` and require passing `--dont-define-prefix` if you want to turn it off. Can pkgconf get some similar option?

I have this working locally by hacking up the Windows `#if` in cli/main.c, but it would be helpful if this behavior also affected programs using libpkgconf, too. An environment variable would also work for my purposes. There's already a `PKG_CONFIG_DONT_RELOCATE_PATHS` to turn it off but there isn't one to turn it on.

**Comment by Neumann-A** [comment]
not necessary. Just fix your pc files using $(pcfiledir) ..... If you don't know how see what vcpkg does to the pc file of e.g. zlib.
