### ISSUE TITLE
proposal: use C99 PRI macro when printing

### ISSUE THREAD

**Issue by vtorri** [pkgconf/pkgconf#262]
As pkgconf is using  C99, what about using C99 PRI macro forr printing messages ?

it requires:
 * inclusion of inttypes.h of stdint.h in stdinc.h (C99 spec says that inttypes.h includes stdint.h)
 * add '-D__USE_MINGW_ANSI_STDIO' in meson.build around line 13 (for MinGW), for example

I can provide a PR is this proposal is accepted

**Comment by kaniini** [comment]
We already use PRI macros where needed.
