### ISSUE TITLE
Should support indented .pc files

### ISSUE THREAD

**Issue by andrewshadura** [pkgconf/pkgconf#265]
In the Debian bug #[1016922](https://bugs.debian.org/1016922) the reporter complains pkgconf cannot find spirv. Upon a closer look, I found that both spirv.pc and glslang.pc are indented by 8 spaces each.

Both pkg-config and ruby-pkg-config seem to be able these just fine; the spec as I understand it is silent on this.

It would probably make sense for pkgconf to support this as well.

Thanks for considering.

**Comment by Tachi107** [comment]
The project has been moved out of GitHub. It's canonical repo is now on a self-hosted Gitea instance: <https://gitea.treehouse.systems/ariadne/pkgconf>
