### ISSUE TITLE
Compared to v1.8.0, `pkgconf --cflags` gives different result in v1.9.3 when `Requires.internal` is used

### ISSUE THREAD

**Issue by 0140454** [pkgconf/pkgconf#269]
I have defined some package config files in this [repository](https://github.com/0140454/pkgconf-config-test).

In shorts,
* `libfoo` internally **requires** (`Requires.internal`) `openssl-3`
* `libbar` internally **requires** (`Requires.internal`) `libcrypto-3`
* `openssl-3` **requires** (`Requires`) `libcrypto-3` and `libssl-3`

And I found that `pkgconf --cflags` gives different result in v1.9.0, comparing to v1.8.0.

In v1.8.0
```
user@localhost /tmp/pkgconf-config-test (git)-[main] % export PKG_CONFIG_PATH=$(pwd); pkg-config --version; pkg-config --cflags libfoo; pkg-config --cflags libbar
1.8.0
-I/usr/local/include 
-I/usr/local/include
```

In v1.9.3
```
user@localhost /tmp/pkgconf-config-test (git)-[main] % export PKG_CONFIG_PATH=$(pwd); pkg-config --version; pkg-config --cflags libfoo; pkg-config --cflags libbar
1.9.3
-I/usr/local/include -I/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/include/openssl-3 
-I/usr/local/include
```

Is it an expected behaviour?

**Comment by 0140454** [comment]
After trying git bisect, the behavior was changed since 197fcadd4c44504808a44fb257275684b5207b10.

If any debug output is needed, I can provide it. Thank you.

**Comment by kaniini** [comment]
Yes, it is known that pkgconf 1.9 has a new solver, which changes output.  This bug report has no actual useful information about what the problem is.
