### ISSUE TITLE
Warnings on OpenIndiana when using meson

### ISSUE THREAD

**Issue by vtorri** [pkgconf/pkgconf#272]
Hello

on OpenIndiana, and I guess all the OS that use the Illumos kernel, strdup() and other functions are not detected with meson. The reason is that illumos is guarding them with the preprocessor macro `__EXTENSIONS__`

so maybe this macro can be added to meson.build both line 11 and 33

Vincent Torri

**Comment by vtorri** [comment]
this can be done conditionnally when a solaris OS is detected.

**Comment by kaniini** [comment]
This is done in 0dde98f.
