### ISSUE TITLE
"-Dtests=false" option for meson build gives error

### ISSUE THREAD

**Issue by tomaquek** [pkgconf/pkgconf#276]
The build instructions for Windows (https://github.com/pkgconf/pkgconf) advise to use the "meson setup build -Dtests=false" command. Running this gives the error:

meson.build:1:0: ERROR: Value "false" (of type "string") for combo option "Build tests which depends upon the kyua framework" is not one of the choices. Possible choices are (as string): "enabled", "disabled", "auto".

The fix appears to be to do as the error message advises, and pass "-Dtests=disabled" instead of "-Dtests=false". So it appears that it's just that the instructions for building on windows are out of date

**Comment by kaniini** [comment]
Fixed in dd741e7.
