### ISSUE TITLE
Building pkgconf with meson doesn't allow to override the system folders

### ISSUE THREAD

**Issue by amyspark** [pkgconf/pkgconf#283]
Hi!

I'm writing to report an issue I found when using pkgconf with Meson https://github.com/mesonbuild/meson/issues/11088.

In short, I build pkgconf along with the rest of the dependencies in a root I control. But when I use it, due to the stripping behaviour, said root will get removed from the include folders, and cause dependent libraries to fail to build or link.

It would be easy to work around this with `PKG_CONFIG_ALLOW_SYSTEM_CFLAGS` (which I use locally), but would it be possible to allow the Meson build system to use the same flags as the autotools system?

(Please note that I'm on Windows, hence why it's not possible to use a POSIX shell.)

**Comment by kaniini** [comment]
If I am understanding correctly, you would like to see the `--with-system-cflags` and `--with-system-libs` (or whatever they are) options ported to the Meson build system?

**Comment by amyspark** [comment]
Yep, currently they're hardcoded to derive from the `prefix`. It makes sense to do that, but in our particular workflow, it also makes `PKG_CONFIG_ALLOW_SYSTEM_CFLAGS` a requirement due to the differing packages and compiler roots.

**Comment by amyspark** [comment]
Linking the original issue from Meson for further context: https://github.com/mesonbuild/meson/issues/11088
