### ISSUE TITLE
`maximum_package_count` is off by one when limiting number of packages to consider

### ISSUE THREAD

**Issue by jashank** [pkgconf/pkgconf#295]
Hello!

Scenario: I have packages `atf-c`, `atf-c++`, `atf-sh`. (Any set of two or more packages works for this trick; I happen to have these three from the same source alphabetically early in my list of packages.)

```shell-session
$ pkgconf --modversion atf-c atf-c++ atf-sh
0.20
0.20
```

... so where did the third one go?

Spelunking the code, I see that `--modversion` (and some other flags) put us into a mode where we only consider one package at a time by setting `maximum_package_count` — perfectly reasonable (though I don't know if this behaviour is actually documented anywhere except here in the source, so surprising in that regard):
https://github.com/pkgconf/pkgconf/blob/78f3abc9359cbe08258c381445b445206b2a0485/cli/main.c#L1113-L1127

However, the logic to actually enforce this erroneously compares cardinal `pkgq.length` to ordinal `maximum_package_count`:
https://github.com/pkgconf/pkgconf/blob/78f3abc9359cbe08258c381445b445206b2a0485/cli/main.c#L1324-L1328

(I stumbled across this bug because [Cabal does this wrong](https://github.com/haskell/cabal/blob/3af1731c01c35614fd902ee5c1aec40f5587fde6/cabal-install-solver/src/Distribution/Solver/Types/PkgConfigDb.hs#L72) then fails for mysterious reasons; I'll also file a bug there about this behaviour.)

**Comment by kaniini** [comment]
Fixed in pending 1.9.5 release.  Thanks!

**Comment by juhp** [comment]
I also stumbled across this today (initially with 1.9.4).
But I don't think it was "off-by-one": 1.9.4 never prints more than two versions!

And 1.9.5 only ever seems to print one version for me.

**Comment by juhp** [comment]
Ah wait you are saying that output one package version now is the correct behavior I see...
Then haskell Cabal needs to be fixed...

And +1 for erroring for more than one package
