### ISSUE TITLE
Unable to download sources from dereferenced.org

### ISSUE THREAD

**Issue by jcar87** [pkgconf/pkgconf#302]
It looks like the server the webserver that serves the source distributions for pkgconf is no longer working, e.g. https://distfiles.dereferenced.org/pkgconf/pkgconf-1.9.3.tar.xz is simply timing out.

This causes problems for package repositories where the canonical sources are expected in this location. Sources from GitHub _could_ be an alternative, however I imagine autoreconf needs to be invoked ahead of calling the configure script, so the contents are not exactly the same. Additionally, there's been issues in the past with GitHub archives not being SHA-stable (even if the contents are), which is a requirement for package repositories.

Any updates on this would be appreciated - or if the original files for the source distributions (with the original contents) could be uploaded as GitHub _release_ artifacts (I believe those _are_ guaranteed to be immutable in terms of hash).

**Comment by danyeaw** [comment]
Could we either use GitHub Releases to post official releases, or is distfiles.dereferenced.org mirrored somewhere? All build systems that depend on downloading pkgconf are down right now.

**Comment by cygauss** [comment]
Google searched out only 2 irrelevant results about distfiles.dereferenced.org in the last 7days. It is amazing that few people find it disappeared, like it never exists.

**Comment by MunyDev** [comment]
Any updates? Buildroot does not work because the mirror is down.

**Comment by kxtzownsu** [comment]
I don't know if the mirror is coming back..
![image](https://github.com/pkgconf/pkgconf/assets/116377025/c223b963-742d-48b2-9c6f-47e4665cba02)

**Comment by kxtzownsu** [comment]
I've found a solution: archive.org

The latest pkgconf backup is 1.7.4

https://web.archive.org/web/20221108000606/https://distfiles.dereferenced.org/pkgconf/pkgconf-1.7.4.tar.xz

**Comment by danyeaw** [comment]
I have mirrored the latest release here: https://github.com/wingtk/gvsbuild/releases/download/pkgconf-1.9.5/pkgconf-1.9.5.tar.gz. I think you could also use a gentoo mirror as well: https://gentoo.osuosl.org/distfiles/pkgconf-1.9.5.tar.xz

**Comment by kxtzownsu** [comment]
All the archives on archive.org are listed here:
https://web.archive.org/web/*/https://distfiles.dereferenced.org/pkgconf*

**Comment by kxtzownsu** [comment]
All the archives are listed [here](https://web.archive.org/web/*/https://distfiles.dereferenced.org/pkgconf*)

Manual Link:
https://web.archive.org/web/*/https://distfiles.dereferenced.org/pkgconf*

**Comment by MunyDev** [comment]
> I have mirrored the latest release here: https://github.com/wingtk/gvsbuild/releases/download/pkgconf-1.9.5/pkgconf-1.9.5.tar.gz. I think you could also use a gentoo mirror as well: https://gentoo.osuosl.org/distfiles/pkgconf-1.9.5.tar.xz

Do you have access to 1.6.5, I need pkgconf 1.6.5 to run buildroot.

**Comment by MunyDev** [comment]
Is there any way to generate the archives, the same one as in the mirror?

**Comment by kumorig** [comment]
Since I got here because gvsbuild build gtk4 breaks because of this, I just have to ask, why does the script fail to verify checksum?
```
https://github.com/pkgconf/pkgconf/archive/refs/tags/pkgconf-1.9.5.tar.gz
3fd0ace7d4398d75f0c566759f9beb4f8b3984fee7ed9804d41c52b193d9745a
```
```
https://distfiles.dereferenced.org/pkgconf/pkgconf-1.9.5.tar.gz
6466efd2e38c4c0ac5de4e345f0dc6dad57e689efb08c31f2a71547683d20dc7
```
should we just assume foul play here? :p

**Comment by danyeaw** [comment]
@kumorig This blog post explains the issue: https://github.blog/2023-02-21-update-on-the-future-stability-of-source-code-archives-and-hashes/

**Comment by jcar87** [comment]
@kumorig - there's also a chance that the tar.gz have different contents - the ones that are a git snapshot may not contain the ./configure script and you need to call autoreconf to generate it, whereas the "source distribution" files hosted on the website do. This is a very typical scenario

**Comment by danyeaw** [comment]
It sounds like @kaniini lost access to the domain, so we'll all need to be patient while they resolve it:
https://social.treehouse.systems/@ariadne/110643909699308207

If you want to unleash us to all to contact Dynadot, let us know.

**Comment by danyeaw** [comment]
It looks like we have a new location: https://github.com/pkgconf/pkgconf/commit/437c2a3218bfcb1cae7fa38a4ccd0cb29575ff07

https://distfiles.ariadne.space/pkgconf/

**Comment by rossburton** [comment]
I endorse uploading the generated tarballs as release artefacts (note I am _not_ talking about the "source code" link which has the issues discussed above).

**Comment by dheater** [comment]
I was in the process of updating the recipe for [Conan](https://conan.io), but I am still getting SSL cert at https://distfiles.ariadne.space/pkgconf/

Recommendations?

**Comment by kxtzownsu** [comment]
> I was in the process of updating the recipe for [Conan](https://conan.io), but I am still getting SSL cert at https://distfiles.ariadne.space/pkgconf/

That's odd... SSL cert seems fine.
