### ISSUE TITLE
SSL error retrieving https://distfiles.ariadne.space/pkgconf/pkgconf-1.9.3.tar.xz

### ISSUE THREAD

**Issue by mphaneufs** [pkgconf/pkgconf#303]
Our build it attempting to download from the new location, but get an SSL error.

ERROR: Error downloading file https://distfiles.ariadne.space/pkgconf/pkgconf-1.9.3.tar.xz: 'HTTPSConnectionPool(host='distfiles.ariadne.space', port=443): Max retries exceeded with url: /pkgconf/pkgconf-1.9.3.tar.xz (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))'

**Comment by dheater** [comment]
I am noticing the same. Reported in this #302 

I can get to the website cleanly and `wget` the file fine from my personal laptop.

From my work machine, I got SSL failures in private mode and from another browser, but the browser problem went away after I disconnected from the VPN. Still can't `wget` from the work machine, but I can from my personal laptop.  Cached certificate somewhere??

**Comment by danyeaw** [comment]
This sounds like this issue: https://stackoverflow.com/questions/52074590/urllib-request-urlopen-ssl-certificate-verify-failed-error-on-windows-vista/52074591#52074591

It isn't an issue with this server, but an issue with how Python is able to use certificates.

For gvsbuild, we attempt the download with SSL. If it raises an exception, we try again without SSL.

**Comment by dheater** [comment]
Cleared up now for me
