### ISSUE TITLE
pkgconf --modversion should error for more than one package

### ISSUE THREAD

**Issue by juhp** [pkgconf/pkgconf#304]
`pkgconf --modversion` allows taking multiple packages but only prints out the version of the first one.

This behavior seems a little strange: I feel it should print out all the versions (like 1.8 used to)
or give up with an error.

See #295 for earlier discussion

**Comment by kaniini** [comment]
We can make it give up with an error, but I would argue that the original pkg-config behavior is a bug here -- the output of `--modversion` is ambiguous when multiple packages are requested.

It should just be an error.

**Comment by kaniini** [comment]
Done in a97b75a
