### ISSUE TITLE
--modversion changed in incompatible way in 2.0.3

### ISSUE THREAD

**Issue by AdrianVovk** [pkgconf/pkgconf#317]
Basically, on versions older than 2.0.3 (tested with 2.0.2 and 1.8.0), `pkg-config --modversion "somelibrary "` (note the extra space) worked exactly the same as `pkg-config --modversion somelibrary` (note lack of extra space).

As if 2,0.3, this behavior has changed. Now, `pkg-config --modversion "somelibrary "` doesn't report any version at all.

Ideally, this wouldn't be an issue. But it looks like some projects have accidentally been relying on this behavior. I understand that those projects should ideally be changed. However, this is an unexpected and undocumented change in behavior for pkgconf. So I'm bringing it to your attention :)

**Comment by AdrianVovk** [comment]
Related bug reports: https://bugs.webkit.org/show_bug.cgi?id=261125

**Comment by negril** [comment]
This is caused by cmake parsing the version specifier incorrectly adding the extra whitespaces you observed. I filed a merge request to fix this upstream at https://gitlab.kitware.com/cmake/cmake/-/merge_requests/8789.

**Comment by xry111** [comment]
You can consider this a cmake issue, but do you really want to print nothing for `pkgconf --modversion "zlib > 1"`?  If you really do, at least you should mention this breaking change in NEWS.

**Comment by negril** [comment]
Cmake is asking for `pkgconf --modversion "zlib " ">" " 1"`. Pay careful attention to the extra whitespace that are very much part of the package id and the version.  If the package or the version don't exist, which they likely won't due to the nonsense whitespace you will get a return value indicating that. Getting other which you would then have to validate is pointless.

**Comment by xry111** [comment]
But with pkgconf 2.0.3, `pkgconf --modversion "zlib" ">" "1"` (without the extra whitespace) does not work either.

You can try it yourself.

**Comment by q234rty** [comment]
Can we reopen this? 962a5e96b7c26217cde16b5b7903090eba3189fe has been effectively reverted by 97d907ba93b7e4eef67e4c0a80939421ad3183f0. I understand the former commit might not be the proper fix, but e.g. `pkgconf --modversion 'glib-2.0 >= 2.78'` still prints nothing on pkgconf 2.1.0. See also #332.

**Comment by nanonyme** [comment]
@kaniini can we please at least have a version *with* this fix (eg 2.0.4) if intent is to change things with 2.1.0? Currently 2.0.2 is the latest functional version of pkgconf.
