### ISSUE TITLE
Requires.internal packages can be not found unless --static is specified

### ISSUE THREAD

**Issue by xclaesse** [pkgconf/pkgconf#318]
I started adding support for Requires.internal in Meson pkg-config generator: https://github.com/mesonbuild/meson/pull/12227.

When `foo.pc` has `Requires.internal: bar` and `bar.pc` is not installed, pkgconf complains with `Package 'bar', required by 'foo', not found`. However, `bar.pc` should only be needed when doing `--libs --static`. The whole point of that field is to remove internal dependencies from build-dep. For example when building an app that uses glib-2.0, we should not have to install zlib dev package.

**Comment by kaniini** [comment]
Not true.  Internal/private dependencies are also needed for any calculation that requires CFLAGS, as the headers may reference the private dependency's headers.

**Comment by xclaesse** [comment]
The whole point of internal dependencies is that headers do not reference them, unlike private deps. You can even check how it's used in pkgconf, it won't put cflags of internal deps.

**Comment by xclaesse** [comment]
This issue should not have been closed.

**Comment by xclaesse** [comment]
I always refers to this post that explains perfectly the 3 types of dependencies: https://bugs.freedesktop.org/show_bug.cgi?id=105572#c1. That's where I initially proposed Require.internal.
