### ISSUE TITLE
[Request] Additional default search paths?

### ISSUE THREAD

**Issue by tfpf** [pkgconf/pkgconf#325]
On my EndeavourOS system with pkgconf 1.8.1:

```console
$ pkg-config --variable pc_path pkg-config
/usr/lib/pkgconfig:/usr/share/pkgconfig
```

Could `/usr/local/share/pkgconfig` and `/usr/local/lib/pkgconfig` be added to that list? Programs compiled from source often go in `/usr/local`, and it would be convenient to automatically search those directories as well. Another justification is that pkg-config does search there! With pkg-config 0.29.2 on Mint, I get:

```console
$ pkg-config --variable pc_path pkg-config
/usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig
```

I don't know if the paths containing `x86_64-linux-gnu` are standard; however, the manual page states following. (Formatting mine.)

> `pkg-config` retrieves information about packages from special metadata files. These files are named after the package, and has a `.pc` extension. On most systems, `pkg-config` looks in `/usr/lib/pkgconfig`, `/usr/share/pkgconfig`, `/usr/local/lib/pkgconfig` and `/usr/local/share/pkgconfig` for these files. It will additionally look in the colon-separated  (on Windows, semicolon-separated) list of directories specified by the `PKG_CONFIG_PATH` environment variable.

I know I can set `PKG_CONFIG_PATH`, but am looking to replace pkg-config with pkgconf without changing an existing project too much.

**Comment by kaniini** [comment]
Use `--with-pkg-config-path=...` configure argument.
