### ISSUE TITLE
Search personality files in XDG_DATA_DIRS

### ISSUE THREAD

**Issue by viccie30** [pkgconf/pkgconf#329]
Depending on how pkgconf is built, personalities are looked for (with normal prefixes) in /usr/share/pkgconfig/personality.d and /etc/pkgconfig/personality.d (https://github.com/pkgconf/pkgconf/blob/752a9825dc8660d247c457aa4d256db4800ebd7c/configure.ac#L34-L37) or /usr/lib/pkgconfig/personality.d and /usr/share/pkgconfig/personality.d (https://github.com/pkgconf/pkgconf/blob/752a9825dc8660d247c457aa4d256db4800ebd7c/meson.build#L47-L50). 

I had hoped that symlinking pkgconf into a toolchain directory's bin subdirectory as `arm-linux-musleabihf-pkg-config` and setting `XDG_DATA_DIRS` would make pkgconf search for personality files (also) in the `pkgconfig/personality.d` subdirectory of every entry in `XDG_DATA_DIRS`. Would this be something you'd be willing to add and/or accept a PR for?

`XDG_DATA_DIRS` is specfied in the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

**Comment by kaniini** [comment]
This isn't supported by original pkg-config, but seems like a useful proposal.  I will go ahead and merge #330.

**Comment by viccie30** [comment]
Thanks for merging the PR! 

It might be worth looking into the different default search paths between autoconf and meson I pointed out. I don't know which of these matches the freedesktop implementation.
