### ISSUE TITLE
2.1.0: Failure to run "cargo install" when building libslirp v4.3.0  (It works fine with 2.0.2)

### ISSUE THREAD

**Issue by jjardon** [pkgconf/pkgconf#335]
See https://gitlab.gnome.org/GNOME/gnome-build-meta/-/jobs/3326165

**Comment by dg0yt** [comment]
Any hint on how this is connected to `pkgconf` 2.1.0? That CI log doesn't help. It doesn't even show direct invocation of `pkgconf`. `pkg-config` may or may not be `pkgconf`.

And there were two major issues with 2.0.2: #322, #327. The update to 2.1.0 might show issues in other spots which where previously hidden by pkgconf issues.

**Comment by Erick555** [comment]
The same problem was introduced in 2.0.3 - it was fixed since then but the fix got silently reverted before 2.1.0 tag: https://github.com/pkgconf/pkgconf/issues/317#issuecomment-1836230890

**Comment by dg0yt** [comment]
I can confirm that there is a problem with `--modversion` output when constraints are used.
