### ISSUE TITLE
[Documentation] Clarifying what pkgconfig is and what is pkg-config

### ISSUE THREAD

**Issue by rubyFeedback** [pkgconf/pkgconf#341]
Hey guys,

LFS has a pkg-config page here:

https://www.linuxfromscratch.org/lfs/view/9.1-systemd/chapter06/pkg-config.html

It calls that package "pkg-config".

Typically one can download this from e. g. here:

https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz

But, this has a last release from 2017. So it feels outdated.

Recently when building a new LFS/BLFS I noticed another pkg-config
version:

https://www.linuxfromscratch.org/lfs/view/development/chapter08/pkgconf.html

However had they name it "Pkgconf-2.1.0" aka "pkgconfig", without pkg-config,
that is, without the "-" hyphen.

I looked at the URL they provide under "All Packages" and found the URL:

https://distfiles.ariadne.space/pkgconf/pkgconf-2.1.0.tar.xz

Using Google Search, though, I found the webpage here, so now I am a bit
confused. I assume the variant here has nothing to do with the one on
distfiles.ariadne.space? Either way, if one of you is motivated, could the
current subsection be clarified a bit? That way we random visitors can
more quickly see whether the variant here, is the one that we want to
try, or whether it is another one instead (such as the one hosted on distfiles.ariadne.space
or anywhere else for that matter).

Right now the main README is a bit confusing in this regard.

**Comment by xry111** [comment]
https://github.com/pkgconf/pkgconf/#release-tarballs:

Release tarballs are available at https://distfiles.ariadne.space/pkgconf/. Please only use the tarballs from distfiles.ariadne.space.

So this is already explicitly explained in README.md.  And the file was last modified 3 months ago but you raised this 2 weeks ago, why didn't you just read the file?

And it's not "we" (the LFS editors) naming it "pkgconf-2.1.0".  The maintainers of pkgconf has named it pkgconf.  We (the LFS editors) have no privilege to change the name of an external project.

Using a tarball (Git snapshot) in the GitHub release page requiring autoconf, which is not available when we build pkgconf in LFS (pkgconf is in LFS section 8.18 and autoconf is in section 8.45).  And the maintainer has already said "only use the tarballs from distfiles.ariadne.space", so we are doing the correct thing.

**Comment by xry111** [comment]
There is indeed something wrong at http://pkgconf.org/: the download link is https://distfiles.dereferenced.org/pkgconf/pkgconf-1.1.0.tar.xz which is old an broken.  (IIRC the hosting of release tarballs has been switched to https://distfiles.ariadne.space/ after the domain name distfiles.dereferenced.org was taken over by someone.)

**Comment by kaniini** [comment]
I don't see any action to take here.  I don't control the pkgconf.org domain, though I have taken a mental note to contact @jdhore and see if he wants to transfer it to me.
