### ISSUE TITLE
incorrect libraries emitted with --static

### ISSUE THREAD

**Issue by WinterMute** [pkgconf/pkgconf#342]
On linux/macOS `PKG_CONFIG_PATH=pkgconfig pkg-config --libs --static freetype2`
gives output of `-L/opt/devkitpro/portlibs/ppc/lib -lfreetype -lbz2 -lpng16 -lz -lm -lz -lharfbuzz -lm`

On windows with pkgconf 2.1.0 the output is `-L/opt/devkitpro/portlibs/ppc/lib -lpng16 -lm -lz -lharfbuzz -lm -L/opt/devkitpro/portlibs/ppc/lib -L/opt/devkitpro/portlibs/ppc/lib -lz -lfreetype -lbz2`

[pkgconfig-test.zip](https://github.com/pkgconf/pkgconf/files/14157320/pkgconfig-test.zip)

**Comment by dg0yt** [comment]
Slightly different results for pkgconf 2.1.0, but confirming the problem. (freetype too late.)
~~~
-L/opt/devkitpro/portlibs/ppc/lib -lpng16 -lm -lz -lm -L/opt/devkitpro/portlibs/ppc/lib -lpng16 -lm -lz -lharfbuzz -lm -lfreetype -lbz2
~~~

With 2.1.1, I see `-freetype` twice:
~~~
-L/opt/devkitpro/portlibs/ppc/lib -lfreetype -lbz2 -lpng16 -lm -lz -lharfbuzz -lm -L/opt/devkitpro/portlibs/ppc/lib -lfreetype -lbz2
~~~

Digraphs are identical:
![img-2 1 1](https://github.com/pkgconf/pkgconf/assets/13567791/8f5bc154-7a63-4007-80f7-fa2ad13b5a2a)

**Comment by dg0yt** [comment]
... so this might be resolved in 2.1.1.

**Comment by kaniini** [comment]
It would be nice to have additional test cases.  Cyclical dependencies were not really ever clearly considered as part of the original pkg-config design.  In my opinion, allowing them was a mistake.

**Comment by WinterMute** [comment]
> With 2.1.1, I see `-freetype` twice:
> 
> ```
> -L/opt/devkitpro/portlibs/ppc/lib -lfreetype -lbz2 -lpng16 -lm -lz -lharfbuzz -lm -L/opt/devkitpro/portlibs/ppc/lib -lfreetype -lbz2
> ```

This is probably correct given the circular dependency between harfbuzz & freetype

**Comment by kaniini** [comment]
Can we test and see if this generates expected output on 2.2.0?  @dg0yt did a lot of work on the solver.

**Comment by dg0yt** [comment]
> On linux/macOS `PKG_CONFIG_PATH=pkgconfig pkg-config --libs --static freetype2` gives output of `-L/opt/devkitpro/portlibs/ppc/lib -lfreetype -lbz2 -lpng16 -lz -lm -lz -lharfbuzz -lm`
> 
> On windows with pkgconf 2.1.0 the output is `-L/opt/devkitpro/portlibs/ppc/lib -lpng16 -lm -lz -lharfbuzz -lm -L/opt/devkitpro/portlibs/ppc/lib -L/opt/devkitpro/portlibs/ppc/lib -lz -lfreetype -lbz2`
> 
> [pkgconfig-test.zip](https://github.com/pkgconf/pkgconf/files/14157320/pkgconfig-test.zip)

With pkgconf 2.2.0:

~~~
$ PKG_CONFIG_PATH=/tmp/pkgconfig ./installed/x64-linux/tools/pkgconf/pkgconf --libs --static freetype2
-L/opt/devkitpro/portlibs/ppc/lib -lfreetype -lbz2 -lpng16 -lm -lz -lharfbuzz -lm
~~~
LGTM. (One `-lz` merged.)

**Comment by kaniini** [comment]
Closing then!
