### ISSUE TITLE
ABI change between 1.9.4 and 2.1.0 without changing SONAME

### ISSUE THREAD

**Issue by ppisar** [pkgconf/pkgconf#347]
After upgrading pkgconf from 1.9.4 to 2.1.0 my application linked to libpkgconf started to crash. The cause is that struct pkgconf_pkg_ changed size and layout. That changed an ABI of the library and the application was accessing an old offset on the structure.

Please bump a SONAME of the library so that applications know that they need to be rebuilt. You need to change -version-info argument in libpkgconf_la_LDFLAGS variable in Makefile.am.

**Comment by dg0yt** [comment]
You may want to test #345 for effects of coming behavioral changes.
- It you use the flattened solution: All flattened deps will be in `requires`, even the private ones (but marked as private).
- Explicitly passed pc files will be added to the internal cache, and are reused if the same name is requested again.

**Comment by thesamesam** [comment]
I'm not saying it shouldn't be changed, but IIRC SONAME did change between 1.8.x and 2.0.x, and 1.9.x was a development series.

**Comment by kaniini** [comment]
Yes, redhat should not have packaged 1.9.x.  It was fairly clearly communicated that it was experimental.

**Comment by thesamesam** [comment]
It was in NEWS, but I agree something clearer would be better for future:
>Changes from 1.8.0 to 1.9.0:
>----------------------------
>
>* pkgconf 1.9.0 is the first testing release in the pkgconf 2.0 development
>  series.  While it is believed to be suitable for production, there may be
>  bugs due to the overall redesign of the solver and other initiatives.
>  Additionally, a future release of pkgconf plans will have additional ABI
>  breaks for the libpkgconf library before the pkgconf 2.0 release is cut.

**Comment by sergiomb2** [comment]
anyway, was not 1.9.x that gave problems,  it was just ABI change on libpkgconf without changing SONAME :smiley:

**Comment by kaniini** [comment]
pkgconf 2.2.0 has been bumped to SOVERSION 5, which should address this.

**Comment by juhp** [comment]
Also apparently 2.1.1 broke ABI relative to 2.1.0 with the addition of the `traverse_serial` field to pkgconf_client_
