### ISSUE TITLE
[BUG] pkgconf adds extraneous trailing white space

### ISSUE THREAD

**Issue by kiplingw** [pkgconf/pkgconf#355]
After several days of headbanging and the help of `strace(1)`, @pabs3 and I were able to track down a problem with the following code failing unexpectedly:

```sh
# Get path to NSS wrapper library... 
nss_wrapper_so_path=$(pkg-config --libs nss_wrapper)

# Check to make sure library path was provided and it's valid...
if [ -z "$nss_wrapper_so_path" ] || [ ! -e "$nss_wrapper_so_path" ] ; then
    echo "Error: Could not locate nss_wrapper library for LD_PRELOAD!"
    exit 1
fi
```

The test for file existence on `"$nss_wrapper_so_path"` was failing, when it should not. The same test worked correctly without quotes. 

With the help of `strace(1)` I found that the cause is pkgconf (1.8.1 on my system) adds an extraneous trailing white space to its output that is not present in the package manifest file for `Libs`. The extra white space is breaking `open(2)` which can't find the file.

I don't know if it was always present, but @pabs3 was able to verify it was present in at least 1.7.4~git20210206+dcf529b-3.

**Comment by pabs3** [comment]
I also noticed that pkg-config did not have this problem,
so the issue could be a compatibility issue for some cases. 

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by dg0yt** [comment]
Apart from newer versions being available:

It  is simply wrong to expect `--libs` (plural!) to return a single filepath. What it returns migh be added to the arguments of another command (or to variables controlling these arguments, such as LIBS), with space as a separator as used by `sh`. A trailing space doesn't hurt for normal use, even if it really shouldn't be there.

...So actually the presented shell code has compatibility issues,

**Comment by kiplingw** [comment]
Is this behaviour consistent with `pkg-config`?

**Comment by dg0yt** [comment]
The output is not expected to be identical letter by letter. But it is expected to have the same effect for proper use.

In particular, pkgconf may change the order of the elements of `--libs` and omit redundant elements.
(There was some struggle with doing this right in the 2.x releases, and it is finally settled in 2.2.0. There are also tests which don't expose a trailing space.)

**Comment by dg0yt** [comment]
Might be fixed since 1.9.4: https://github.com/pkgconf/pkgconf/commit/648a2249fcb10bf679bdb587ef2bbddaab3023ad

**Comment by kiplingw** [comment]
I can confirm as of 2.2.0 (2d26db3a984e7a69cedc6274c22119de4bcf1b40) that the trailing space is still there.

**Comment by dg0yt** [comment]
> I can confirm as of 2.2.0 ([2d26db3](https://github.com/pkgconf/pkgconf/commit/2d26db3a984e7a69cedc6274c22119de4bcf1b40)) that the trailing space is still there.

That would be surprising. My test case is fine:
~~~
$ echo "'$(installed/x64-linux/tools/pkgconf/pkgconf installed/x64-linux/lib/pkgconfig/zlib.pc --libs)' [$(installed/x64-linux/tools/pkgconf/pkgconf --version)]"
'-Linstalled/x64-linux/lib/pkgconfig/../../lib -lz' [2.2.0]
~~~

**Comment by kiplingw** [comment]
Downloading and building source:
```
$ git clone https://github.com/pkgconf/pkgconf.git
$ cd pkgconf/
$ ./autogen.sh
$ mkdir -p {prefix,build}
$ cd build
$ ../configure --prefix=$PWD/../prefix
$ make -j
```

Showing trailing space:
```
$ alias whitespace="sed 's/ /·/g;s/\t/￫/g;s/\r/§/g;s/$/¶/g'"
$ PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig/ pkg-config --libs nss_wrapper | whitespace
/usr/lib/x86_64-linux-gnu/libnss_wrapper.so·¶
```

Verifying trailing white space is not in package manifest file:
```
$ cat /usr/lib/x86_64-linux-gnu/pkgconfig/nss_wrapper.pc | whitespace
Name:·nss_wrapper¶
Description:·The·nss_wrapper·library¶
Version:·1.1.15¶
Libs:·/usr/lib/x86_64-linux-gnu/libnss_wrapper.so¶
```

Using pkgconf version:
```
$ ./pkgconf --version
2.2.0
```

**Comment by dg0yt** [comment]
~~~diff
-PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig/ pkg-config --libs nss_wrapper | whitespace
+PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig/ ./pkgconf --libs nss_wrapper | whitespace

**Comment by kiplingw** [comment]
Sorry, I can confirm with HEAD that the issue appears to have been fixed:

```
$ PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig/ ./pkgconf --libs nss_wrapper | whitespace
/usr/lib/x86_64-linux-gnu/libnss_wrapper.so¶
```
