### ISSUE TITLE
[Feature request] Add -D option to test for for optional dependencies

### ISSUE THREAD

**Issue by fragglet** [pkgconf/pkgconf#356]
Use case: I am writing a program that has an optional dependency on a library that is made available with pkgconf. In my program I want to be able to do something like this:
```c
#ifdef HAVE_LIBOPTIONALDEP
#include "liboptionaldep.h"
#endif /* #ifdef HAVE_LIBOPTIONALDEP */

...

#ifdef HAVE_LIBOPTIONALDEP
    // Some code that uses the library
    optionaldep_foobar();
#endif /* #ifdef HAVE_LIBOPTIONALDEP */
```
Autotools provides macros for doing this kind of thing, but it would be really nice if I could do something like this in a plain Makefile:
```make
CFLAGS = $(pkg-config --optional --cflags liboptionaldep) $(pkg-config --cflags requireddeps)
LDFLAGS = $(pkg-config --optional --libs liboptionaldep) $(pkg-config --libs requireddeps)
```
If the `--optional` parameter is provided, the following happen, different to the normal program behavior:

1. It is no longer an error if any dependencies specified on the command line are not found on the system; no error messages are printed and the program exits with 0 status code
2. If the dependency is found, `--cflags` option appends `-DHAVE_${PACKAGENAME}` (substitute for the library name as appropriate) to the normal argument list
3. The same variable is appended to `--libs` (this part probably not necessary?)

There could maybe be some additional argument to specify the form of the preprocessor variable, but probably hard-coding `HAVE_{PACKAGENAME}` would be fine for most cases.

Is this an enhancement you'd be willing to include in the program?

**Comment by kaniini** [comment]
`--fragment-filter=D` already does this:

```
pestilence:~/pkgconf$ cat tests/lib1/foo.pc
prefix=/test
exec_prefix=${prefix}
libdir=${prefix}/lib
includedir=${prefix}/include

Name: foo
Description: A testing pkg-config file
Version: 1.2.3
Libs: -L${libdir} -lfoo
Cflags: -fPIC -I${includedir}/foo
Cflags.private: -DFOO_STATIC
License: ISC
pestilence:~/pkgconf$ ./pkgconf --fragment-filter=D tests/lib1/foo.pc --cflags --static
-DFOO_STATIC
```

**Comment by kaniini** [comment]
Sorry, I misread your ask.  It seems interesting, but would be a challenge to integrate at the moment.

**Comment by fragglet** [comment]
In the meantime [I have managed to devise a way of achieving this](https://github.com/fragglet/WadGadget/blob/trunk/GNUmakefile#L3):
```make

LIBSIXEL_CFLAGS = \
    $(shell pkg-config --silence-errors --cflags libsixel \
   && echo -DHAVE_LIBSIXEL)
LIBSIXEL_LDFLAGS = \
    $(shell pkg-config --silence-errors --libs libsixel)
```
It would still be nice to have it as a proper option to pkgconf.

**Comment by kaniini** [comment]
Added `pkgconf --exists-cflags` which adds `-DHAVE_<capitalized module name>` fragments to the rendered CFLAGS for a solution in d76aa35.
