### ISSUE TITLE
Misuse of isspace in cli/main.c apply_modversion

### ISSUE THREAD

**Issue by riastradh** [pkgconf/pkgconf#357]
The commit https://github.com/pkgconf/pkgconf/commit/b2f8386c32d1cb4dfa8f51c619c0c2a56a3544d6 introduced a call to isspace on a value of type char without casting to unsigned char first:

https://github.com/pkgconf/pkgconf/blob/b2f8386c32d1cb4dfa8f51c619c0c2a56a3544d6/cli/main.c#L340

This is potential undefined behaviour, because the isspace function is defined only on value of type int that are either (a) the value of the macro EOF, or (b) representable by the type unsigned char.  To use isspace and the other ctype.h functions safely on all inputs of type char, you must cast to unsigned char first.  See https://github.com/pkgconf/pkgconf/issues/291 for more details, from the last time I went through and systematically eliminated this undefined behaviour in the source tree as it existed a year ago.

**Comment by kaniini** [comment]
Fixed in 633433b
