### ISSUE TITLE
pkgconf-2.2.0: not using more modules from [list of modules]

### ISSUE THREAD

**Issue by art-latal** [pkgconf/pkgconf#366]
Unexpected behaviour change between versions 1.6.3 and 2.2.0 when using --print-requires argument with multiple modules. Seems that behaviour changed when version 2.X was introduced. There was no change to man pages, which leads me to conclusion that this is unwanted regression. 

Wrong behaviour:

```
$ pkg-config --version
2.2.0
```

```
$ pkg-config --print-requires atk
glib-2.0 >= 2.67.4
gobject-2.0 >= 2.0.0
```

```
$ pkg-config --print-requires atspi-2
dbus-1 >= 1.5
glib-2.0 >= 2.67.4
```

```
$ pkg-config --print-requires atk atspi-2
glib-2.0 >= 2.67.4
gobject-2.0 >= 2.0.0
```
^^^ here is missing print-requires for atspi-2

Correct behaviouir (with old version):
```
$ pkg-config --version
1.6.3
```

```
$ pkg-config --print-requires atk atspi-2
glib-2.0 >= 2.38.0
gobject-2.0 >= 2.38.0
dbus-1
glib-2.0
```

Reproducible: Always

(original report was filed on [Gentoo Bugzilla bug 939814](https://bugs.gentoo.org/939814))

**Comment by kaniini** [comment]
Yes, this is likely related to the use of the flattener.  I will look into this later this week as I am planning to cut another pkgconf release.

**Comment by dg0yt** [comment]
Can a test be added for this bug and change?
