### ISSUE TITLE
Relocating paths from .pc files on Windows

### ISSUE THREAD

**Issue by Alexpux** [pkgconf/pkgconf#72]
Hi!

I'm developer of MSYS2 project. Builded software have always UNIX paths in .pc files. Under MSYS in most cases it's ok because it convert paths where spawn native Win32 process but sometimes we have problems. For example using cmake or building python modules.
In this case cmake/python call pkgconf and get UNIX paths. As cmake and python is native win32 programs converting paths not happen when, for example, python distutils spawn GCC.
To resolve this issue I try to expand paths reading from .pc file in pkgconf itself:
https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-pkgconf/0002-relocate.patch

It work in general ok but only for packages without dependencies:
c:\msys64\mingw64\bin>pkg-config --cflags-only-I harfbuzz
-Ic:/msys64/mingw64/include/harfbuzz

But for packages with dependencies not all paths are relocated:
c:\msys64\mingw64\bin>pkg-config --cflags-only-I gtk+-3.0
-Ic:/msys64/mingw64/include/gtk-3.0 -Ic:/msys64/mingw64/include/harfbuzz -Ic:/msys64/mingw64/include/pango-1.0 -Ic:/msys64/mingw64/include/cairo -Ic:/msys64/mingw64/include/pixman-1 -I/mingw64/include/libpng16 -I/mingw64/include/harfbuzz -Ic:/msys64/mingw64/include -I/mingw64/include/freetype2 -Ic:/msys64/mingw64/include/gdk-pixbuf-2.0 -Ic:/msys64/mingw64/include/libpng16 -IC:/msys64/mingw64/include/atk-1.0 -Ic:/msys64/mingw64/include/glib-2.0 -Ic:/msys64/mingw64/lib/glib-2.0/include

Can any one help with this?

Regards,
Alexey.

**Comment by kaniini** [comment]
I'd like to solve this cleanly for 0.10.  Can you explain how the pathtools work?

**Comment by Alexpux** [comment]
@kaniini, hi!
Pathtools is just set of procedures that can create proper paths for application if it hardcoded.
For example:
1. We configure application with ````--prefix=/usr````.
2. Automake system provide
````BINDIR=/usr/bin````
````LIBDIR=/usr/lib````
3. Application use ````BINDIR```` and ````LIBDIR```` that is hardcoded after building.

Our pathtools try to relocate this paths by create new valid path basing on hardcoded values (for example, BINDIR and LIBDIR).
1. We get current path of executable  (our new BINDIR)
2. Create relative path from hardcoded BINDIR and LIBDIR.
3. Merge new BINDIR with relative path
4. Simplify path.

There are some patches that we done for relocating applications:
https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-p11-kit/0006-p11-kit-relocation.patch
https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-openssl/openssl-1.0.1i-relocation.patch
https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-imagemagick/001-relocate.patch
https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-pkgconf/0002-relocate.patch

P.S.: For nowadays we back to use original ````pkg-config```` utility as ````pkgconf```` have some issues that we can;t solve ourselves

**Comment by kaniini** [comment]
So a problem with this approach is, if you have a MSYS on `C:\msys2\` for example, and your pkg-config modules are in `/d/blah/blah` then your patch does not convert to `D:\blah\blah`.

I am looking into a solution.

**Comment by kaniini** [comment]
The new `pkgconf_path_relocate()` API handles this on cygwin derivatives, including MSYS2.

**Comment by yselkowitz** [comment]
We do **not** want to use Windows paths on Cygwin itself (on which *NIX paths should be used), only on MSYS.  Please change the `HAVE_CYGWIN_CONV_PATH` conditionals to `__MSYS__`.

**Comment by kaniini** [comment]
@yselkowitz out of curiosity is __CYGWIN__ declared on msys?

**Comment by kaniini** [comment]
argh i meant `__CYGWIN__`

**Comment by Alexpux** [comment]
It is declared.

**Comment by kaniini** [comment]
The requested change will be included in the 1.2.2 release.
