### ISSUE TITLE
tutorial/docs

### ISSUE THREAD

**Issue by techtonik** [pkgconf/pkgconf#77]
I understand that `pkgconf` if a replacement for some good and old unix tool, but is it possible to host some straight-to-the point tutorial that describes the problem domain for those with no prior experience?

**Comment by kaniini** [comment]
Would be nice but right now I don't have time to write documentation.  If someone else does it, I will merge it.

**Comment by kaniini** [comment]
In meantime, you could read legacy `pkg-config`'s tutorial: http://people.freedesktop.org/~dbn/pkg-config-guide.html

**Comment by techtonik** [comment]
From that page - `pkg-config collects metadata about the installed
libraries on the system`. Is it obligatory to install the libraries? I just
want to point to the location of dependencies in downloadable .zip file, so
that after unpacking I can add its directories to appropriate INCLUDE and
LIB paths.

**Comment by kaniini** [comment]
Yes, `pkg-config` is not a package manager in any way.  Nor is `pkgconf`, but a package manager as you describe could be built around it (although this seems like a bad idea)

**Comment by techtonik** [comment]
On Fri, Jun 26, 2015 at 10:17 AM, William Pitcock <notifications@github.com>
wrote:

> Yes, pkg-config is not a package manager in any way. Nor is pkgconf, but
> a package manager as you describe could be built around it (although this
> seems like a bad idea)
>

Why it is a bad idea? I need the libraries only for the build process, and
see how much magic is required to set all those paths correctly for the
build -
https://bitbucket.org/techtonik/locally/src/48cd31a64c9ec8b198e2b4c9d394d43c45d65bcd/05.wesnoth.py?at=default#cl-419
- and imagine how many days I spent trying to figure this out.

**Comment by techtonik** [comment]
Just to clarify - I don't need package manager. I need a format to describe
the paths to different libraries in the archive.

**Comment by kaniini** [comment]
As mentioned previously, that's not what `pkg-config` nor `pkgconf` do.  It's a toolchain tool, what you would probably want to do is have virtual entries in your package database based on .pc files provided.  That is what redhat, alpine, etc do.  Don't know why Debian hasn't joined that party yet.

**Comment by techtonik** [comment]
Is pkgconf data format suitable for that purpose? I'd like to avoid writing the stuff from scratch if possible.

**Comment by kaniini** [comment]
you don't even need the data, you just index by what package has what .pc file, and then that allows you to build an index of providers.
