### ISSUE TITLE
RFC: replacing the custom buildsystem with automake/libtool

### ISSUE THREAD

**Issue by kaniini** [pkgconf/pkgconf#79]
In order to facilitate portably splitting out the pkgconf parser/module-handler/resolver from the main app, I would like to use libtool, since it won't require installing any special tools on a system (i.e. to build from the tarball).

Thoughts?

cc: @bapt, @jdhore

**Comment by bapt** [comment]
fine with me

**Comment by jdhore** [comment]
sounds good to me
