### ISSUE TITLE
Support environment variable PKG_CONFIG_SYSTEM_INCLUDE_PATH

### ISSUE THREAD

**Issue by dankegel** [pkgconf/pkgconf#86]
Evidently some users depend on 
PKG_CONFIG_SYSTEM_INCLUDE_PATH
See
https://bugs.freedesktop.org/attachment.cgi?id=45162
for the rationale behind that environement variable.
See
http://lists.freedesktop.org/archives/pkg-config/2016-January/001033.html
for an example of a user who needed it (to build MythTV on Mac... dirty situation).

**Comment by kaniini** [comment]
Ouch.  That is not in the manpage...
