### ISSUE TITLE
Missing feature to write log with PKG_CONFIG_LOG envronment variable

### ISSUE THREAD

**Issue by obache** [pkgconf/pkgconf#88]
pkg-config support logging how required modules were checked.
It will be enabled if PKG_CONFIG_LOG environment variable is defined and its name is the log file name.

Such feature is useful to detect missing optional dependencies, and vice versa, detect unwanted optional dependencies.

Output formats should be same as pkg-config and it allow to reuse existing log file parser.

**Comment by kaniini** [comment]
pkg-config git's implementation of this seems very incomplete.  is it *really* that useful?  can you show me some examples of it in action?

**Comment by obache** [comment]
I'm using [vefifypc](http://pkgsrc.se/pkgtools/verifypc) from pkgsrc to sanity check dependencies.
