### ISSUE TITLE
Strange path lookups resulting in no directories or files found

### ISSUE THREAD

**Issue by Earnestly** [pkgconf/pkgconf#89]
To cut things short, I packaged this with `./configure --prefix=/usr` along with `make`, `make DESTDIR="$pkgdir" install` and included the `pkg-config` symlink.

However I get the following errors:

```
% pkg-config --cflags --libs wlc
Package wlc was not found in the pkg-config search path.
Perhaps you should add the directory containing `wlc.pc'
to the PKG_CONFIG_PATH environment variable
Package 'wlc', required by 'world', not found
```

*[What is this 'world' that `pkgconf` is referring to?]*

So I threw it at strace and found it looking in rather odd places:

```
open("${exec_prefix}/lib/pkgconfig/wlc-uninstalled.pc", O_RDONLY) = -1 ENOENT (No such file or directory)
open("${exec_prefix}/lib/pkgconfig/wlc.pc", O_RDONLY) = -1 ENOENT (No such file or directory)
open("${datarootdir}/pkgconfig/wlc-uninstalled.pc", O_RDONLY) = -1 ENOENT (No such file or directory)
open("${datarootdir}/pkgconfig/wlc.pc", O_RDONLY) = -1 ENOENT (No such file or directory)
```

It seems as if these strings are not being expanded correctly in the Makefile and ending up in the final binary:

```
% strings pkgconf | grep exec
${exec_prefix}/lib
...
```

I suppose a work around for this might be to explicitly set these via `./configure`.  Ideally I'd not want to define `PKG_CONFIG_PATH=/usr/lib/pkgconfig:/usr/share/pkgconfig` explicitly in my environment when those should be the defaults.

*PS: If you need any more information about my environment just ask, I wasn't sure what to include, if it was relevant.*

**Comment by Earnestly** [comment]
Scratch that about explicitly setting `--exec-prefix`, only `--datadir` seems to work as I now get:

```
open("${exec_prefix}/lib/pkgconfig/wlc-uninstalled.pc", O_RDONLY) = -1 ENOENT (No such file or directory)
open("${exec_prefix}/lib/pkgconfig/wlc.pc", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/pkgconfig/wlc-uninstalled.pc", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/pkgconfig/wlc.pc", O_RDONLY) = -1 ENOENT (No such file or directory)
```

**Comment by kaniini** [comment]
What version did you build, what shell?

**Comment by Earnestly** [comment]
The build from commit https://github.com/pkgconf/pkgconf/commit/7e6fa325eb668c3462981a16fb4c36270832e00f and the shell used to build it was bash.

**Comment by Earnestly** [comment]
Lovely, that works.  Thank you o/
