### ISSUE TITLE
pkg-config bug on creating a new project in Eclipse Neon

### ISSUE THREAD

**Issue by damien022** [pkgconf/pkgconf#91]
Just installed pkg-config in Eclipse-Neon, on Windows 10
It works fine on an existing project and creates the correct links, however when wanting to create a new C++ project, Eclipse throws a null pointer exception. I tried on a fresh install of Eclipse, with only pkg-config installed and got the same error

**Comment by kaniini** [comment]
I think you're reporting this in the wrong place, sorry.

**Comment by damien022** [comment]
yes my apologies!
