### ISSUE TITLE
help broken configure scripts

### ISSUE THREAD

**Issue by 0-wiz-0** [pkgconf/pkgconf#93]
Since the pkg-config version has been 0.9.0 for ages, people have been writing tests expecting the version number to be in that format.
The latest pkgconf release, 1, just returns "1" as version number, which breaks some of these (unwarranted) expectations. This breaks e.g. compilation of lilypond.
Can you please make it return version '1.0.0' instead?

**Comment by kaniini** [comment]
lilypond upstream is already fixing the issue.  i rather fix the unwarranted expectations in other packages.  do you have a list of regressions?

we tested this change with freebsd ports tinderbox about a year ago and didn't observe any other breakage than lilypond.

**Comment by 0-wiz-0** [comment]
I haven't found any other yet, and since you say lilypond is fixed, let's just fix the others too.
