### ISSUE TITLE
Include paths specified with -isystem are not mangled

### ISSUE THREAD

**Issue by yann-morin-1998** [pkgconf/pkgconf#94]
When a .pc file specifies include paths using `-isystem`, those paths
are not prefixed with `PKG_CONFIG_SYSROOT_DIR`.

For example, the [libbsd-overlay.pc](https://cgit.freedesktop.org/libbsd/tree/src/libbsd-overlay.pc.in) (from [libbsd](https://libbsd.freedesktop.org/wiki/)) contains:

    Cflags: -isystem ${includedir}/bsd -DLIBBSD_OVERLAY

Which when in cross-compilation causes build failures because the path
isn't prefixed with `PKG_CONFIG_SYSROOT_DIR` and thus points to the
build system headers (if they are present).

**Comment by kaniini** [comment]
What does ${includedir} look like in that .pc file?  It may need to be fixed.

**Comment by yann-morin-1998** [comment]
Hello,

Here is the `libbsd-overlay.pc` as installed:

    prefix=/usr
    exec_prefix=/usr
    libdir=${exec_prefix}/lib
    includedir=${prefix}/include
    
    Name: libbsd
    Description: Utility functions from BSD systems (overlay)
    Version: 0.8.3
    URL: https://libbsd.freedesktop.org/
    Libs: -L${libdir} -lbsd
    Cflags: -isystem ${includedir}/bsd -DLIBBSD_OVERLAY

Regards,
Yann E. MORIN.

**Comment by kaniini** [comment]
Interesting.  I'll see what I can do.

**Comment by yann-morin-1998** [comment]
Great, thanks!

If you need testing, do not hesitate to ask!

Regards,
Yann E. MORIN.

**Comment by yann-morin-1998** [comment]
Hello again,

I was looking back at this issue, and did some experiment. I just noticed that, when
replacing `-isystem` with just `-I`, the path was not mangled either:

    Cflags: -I ${includedir}/bsd -DLIBBSD_OVERLAY

    $ PKG_CONFIG_SYSROOT_DIR=/some/path pkgconf --cflags libbsd-overlay
    -I /usr/include/bsd -DLIBBSD_OVERLAY

But now, if I remove the space between `-I` and the path, it works:

    Cflags: -I${includedir}/bsd -DLIBBSD_OVERLAY

    $ PKG_CONFIG_SYSROOT_DIR=/some/path pkgconf --cflags libbsd-overlay
    -I/some/path/usr/include/bsd -DLIBBSD_OVERLAY

It is perfectly valid for `-I` to be followed by a space.

The issue also happens for `-L` if it is followed by a space, which is also perfectly valid.

Should I open a different issue for those?

Regards,
Yann E. MORIN.

**Comment by kaniini** [comment]
We are still examining the situation!

**Comment by yann-morin-1998** [comment]
Thanks! :-)

I'll be testing that soon!

Regards,
Yann E. MORIN.
